# Generated by Django 4.2.27 on 2026-01-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch", models.CharField(max_length=100, verbose_name="分支")),
                (
                    "commit_hash",
                    models.CharField(max_length=40, verbose_name="Commit Hash"),
                ),
                ("commit_message", models.TextField(blank=True, verbose_name="提交信息")),
                ("author", models.CharField(max_length=100, verbose_name="作者")),
                (
                    "author_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="作者邮箱"),
                ),
                ("commit_time", models.DateTimeField(verbose_name="提交时间")),
                ("risk_score", models.FloatField(verbose_name="风险评分(0-1)")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("HIGH", "高风险"), ("MEDIUM", "中风险"), ("LOW", "低风险")],
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                ("ai_review_content", models.TextField(verbose_name="AI评审内容")),
                (
                    "ai_model",
                    models.CharField(
                        default="deepseek-coder", max_length=50, verbose_name="使用的AI模型"
                    ),
                ),
                ("changed_files", models.JSONField(verbose_name="变更文件列表")),
                ("diff_content", models.TextField(blank=True, verbose_name="Diff内容")),
                ("review_points", models.JSONField(default=list, verbose_name="评审要点")),
                (
                    "feedback_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待反馈"),
                            ("CORRECT", "评审准确"),
                            ("FALSE_POSITIVE", "误报"),
                            ("MISSED", "漏报"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="反馈状态",
                    ),
                ),
                ("feedback_comment", models.TextField(blank=True, verbose_name="反馈评论")),
                (
                    "feedback_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="反馈时间"),
                ),
                (
                    "dingtalk_sent",
                    models.BooleanField(default=False, verbose_name="是否已推送钉钉"),
                ),
                (
                    "dingtalk_sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="钉钉推送时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评审时间"),
                ),
            ],
            options={
                "verbose_name": "代码评审",
                "verbose_name_plural": "代码评审记录",
                "db_table": "code_review",
            },
        ),
    ]
