# Generated by Django 4.2.27 on 2026-01-20 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("code_review", "0001_initial"),
        ("repository", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codereview",
            name="feedback_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="反馈人",
            ),
        ),
        migrations.AddField(
            model_name="codereview",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="repository.repository",
                verbose_name="仓库",
            ),
        ),
        migrations.AddIndex(
            model_name="codereview",
            index=models.Index(
                fields=["repository", "branch"], name="code_review_reposit_f68da5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codereview",
            index=models.Index(
                fields=["risk_level"], name="code_review_risk_le_a8e9f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codereview",
            index=models.Index(
                fields=["created_at"], name="code_review_created_3640a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codereview",
            index=models.Index(fields=["author"], name="code_review_author_aa1689_idx"),
        ),
        migrations.AddIndex(
            model_name="codereview",
            index=models.Index(
                fields=["feedback_status"], name="code_review_feedbac_780623_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="codereview",
            unique_together={("repository", "commit_hash")},
        ),
    ]
