# Generated by Django 4.2.27 on 2026-01-20 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("repository", "0002_initial"),
        ("code_review", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Celery任务ID"
                    ),
                ),
                ("branch", models.CharField(max_length=100, verbose_name="分支")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待中"),
                            ("RUNNING", "进行中"),
                            ("CLONING", "克隆仓库中"),
                            ("FETCHING", "获取提交记录中"),
                            ("DIFFING", "分析代码差异中"),
                            ("REVIEWING", "AI评审中"),
                            ("SAVING", "保存评审结果中"),
                            ("NOTIFYING", "发送钉钉通知中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "current_step",
                    models.CharField(blank=True, max_length=200, verbose_name="当前步骤"),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度百分比")),
                ("total_commits", models.IntegerField(default=0, verbose_name="总提交数")),
                (
                    "processed_commits",
                    models.IntegerField(default=0, verbose_name="已处理提交数"),
                ),
                (
                    "high_risk_count",
                    models.IntegerField(default=0, verbose_name="高风险提交数"),
                ),
                (
                    "medium_risk_count",
                    models.IntegerField(default=0, verbose_name="中风险提交数"),
                ),
                (
                    "low_risk_count",
                    models.IntegerField(default=0, verbose_name="低风险提交数"),
                ),
                (
                    "dingtalk_notified_count",
                    models.IntegerField(default=0, verbose_name="钉钉通知数"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.repository",
                        verbose_name="仓库",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发人",
                    ),
                ),
            ],
            options={
                "verbose_name": "评审任务",
                "verbose_name_plural": "评审任务进度",
                "db_table": "review_task",
                "indexes": [
                    models.Index(
                        fields=["task_id"], name="review_task_task_id_5969b8_idx"
                    ),
                    models.Index(
                        fields=["status"], name="review_task_status_50cf55_idx"
                    ),
                    models.Index(
                        fields=["repository"], name="review_task_reposit_4ad4f0_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="review_task_created_8f51b8_idx"
                    ),
                ],
            },
        ),
    ]
