# Generated by Django 4.2.27 on 2026-01-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("code_review", "0003_reviewtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="codereview",
            name="lines_added",
            field=models.IntegerField(default=0, verbose_name="新增行数"),
        ),
        migrations.AddField(
            model_name="codereview",
            name="lines_changed",
            field=models.IntegerField(default=0, verbose_name="变更总行数"),
        ),
        migrations.AddField(
            model_name="codereview",
            name="lines_deleted",
            field=models.IntegerField(default=0, verbose_name="删除行数"),
        ),
    ]
