# Generated by Django 4.2.27 on 2026-01-23 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0003_repository_review_all_branches_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "code_review",
            "0004_codereview_lines_added_codereview_lines_changed_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RealtimeMonitorConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="是否启用")),
                (
                    "monitored_branches",
                    models.JSONField(
                        default=list,
                        help_text='例如: ["master", "develop"]',
                        verbose_name="监控分支",
                    ),
                ),
                (
                    "check_interval",
                    models.IntegerField(
                        default=60, help_text="多久检查一次新提交", verbose_name="检查间隔（秒）"
                    ),
                ),
                (
                    "last_checked_commit",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="最后检查的Commit"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后检查时间"),
                ),
                ("auto_review", models.BooleanField(default=True, verbose_name="自动评审")),
                (
                    "notify_on_new_commit",
                    models.BooleanField(default=True, verbose_name="新提交时通知"),
                ),
                (
                    "notify_level",
                    models.CharField(
                        choices=[("HIGH", "高风险"), ("MEDIUM", "中风险"), ("LOW", "低风险")],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="通知级别",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "实时监控配置",
                "verbose_name_plural": "实时监控配置",
                "db_table": "realtime_monitor_config",
            },
        ),
        migrations.CreateModel(
            name="ScheduledReviewConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "cron_expression",
                    models.CharField(
                        help_text="例如: 0 12 * * * (每天中午12点)",
                        max_length=100,
                        verbose_name="Cron表达式",
                    ),
                ),
                (
                    "branches",
                    models.JSONField(
                        default=list,
                        help_text='例如: ["master", "develop"]',
                        verbose_name="评审分支",
                    ),
                ),
                (
                    "review_all_branches",
                    models.BooleanField(default=False, verbose_name="评审所有分支"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "notify_on_complete",
                    models.BooleanField(default=True, verbose_name="完成后通知"),
                ),
                (
                    "notify_webhook",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="通知Webhook"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后运行时间"),
                ),
            ],
            options={
                "verbose_name": "定时评审配置",
                "verbose_name_plural": "定时评审配置",
                "db_table": "scheduled_review_config",
            },
        ),
        migrations.AddField(
            model_name="codereview",
            name="trigger_mode",
            field=models.CharField(
                choices=[
                    ("MANUAL", "手动触发"),
                    ("SCHEDULED", "定时任务"),
                    ("REALTIME", "实时监控"),
                    ("WEBHOOK", "Webhook触发"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="触发模式",
            ),
        ),
        migrations.AddField(
            model_name="codereview",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="触发人",
            ),
        ),
        migrations.AddField(
            model_name="reviewtask",
            name="trigger_mode",
            field=models.CharField(
                choices=[
                    ("MANUAL", "手动触发"),
                    ("SCHEDULED", "定时任务"),
                    ("REALTIME", "实时监控"),
                    ("WEBHOOK", "Webhook触发"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="触发模式",
            ),
        ),
        migrations.AddIndex(
            model_name="codereview",
            index=models.Index(
                fields=["trigger_mode"], name="code_review_trigger_f32a9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewtask",
            index=models.Index(
                fields=["trigger_mode"], name="review_task_trigger_b44dfa_idx"
            ),
        ),
        migrations.AddField(
            model_name="scheduledreviewconfig",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="scheduledreviewconfig",
            name="repositories",
            field=models.ManyToManyField(
                to="repository.repository", verbose_name="关联仓库"
            ),
        ),
        migrations.AddField(
            model_name="realtimemonitorconfig",
            name="repository",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="repository.repository",
                verbose_name="仓库",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledreviewconfig",
            index=models.Index(
                fields=["is_active"], name="scheduled_r_is_acti_563936_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledreviewconfig",
            index=models.Index(
                fields=["last_run_at"], name="scheduled_r_last_ru_31b2c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realtimemonitorconfig",
            index=models.Index(
                fields=["is_active"], name="realtime_mo_is_acti_0dfbb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realtimemonitorconfig",
            index=models.Index(
                fields=["last_checked_at"], name="realtime_mo_last_ch_cb09dc_idx"
            ),
        ),
    ]
