# Generated by Django 3.2.25 on 2026-02-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_review', '0005_realtimemonitorconfig_scheduledreviewconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtask',
            name='status',
            field=models.CharField(choices=[('PENDING', '等待中'), ('RUNNING', '进行中'), ('CLONING', '克隆仓库中'), ('FETCHING', '获取提交记录中'), ('DIFFING', '分析代码差异中'), ('REVIEWING', 'AI评审中'), ('SAVING', '保存评审结果中'), ('NOTIFYING', '发送钉钉通知中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='任务状态'),
        ),
    ]
