# Generated by Django 4.2.27 on 2026-01-30 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="文档标题")),
                ("description", models.TextField(blank=True, verbose_name="文档描述")),
                (
                    "file",
                    models.FileField(upload_to="knowledge_docs/", verbose_name="文档文件"),
                ),
                ("file_name", models.CharField(max_length=200, verbose_name="原始文件名")),
                ("file_type", models.CharField(max_length=20, verbose_name="文件类型")),
                ("file_size", models.IntegerField(verbose_name="文件大小（字节）")),
                ("content", models.TextField(verbose_name="文档内容")),
                (
                    "structured_data",
                    models.JSONField(default=dict, verbose_name="结构化数据"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "处理失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("section_count", models.IntegerField(default=0, verbose_name="章节数量")),
                ("keyword_count", models.IntegerField(default=0, verbose_name="关键词数量")),
                ("entity_count", models.IntegerField(default=0, verbose_name="实体数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理完成时间"),
                ),
            ],
            options={
                "verbose_name": "知识库文档",
                "verbose_name_plural": "知识库文档",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="实体名称")),
                ("entity_type", models.CharField(max_length=50, verbose_name="实体类型")),
                ("description", models.TextField(blank=True, verbose_name="实体描述")),
                ("confidence", models.FloatField(default=0.0, verbose_name="置信度")),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "知识实体",
                "verbose_name_plural": "知识实体",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField(verbose_name="查询文本")),
                ("response_text", models.TextField(blank=True, verbose_name="响应文本")),
                ("search_results", models.JSONField(default=list, verbose_name="搜索结果")),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, verbose_name="置信度"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "related_documents",
                    models.ManyToManyField(
                        blank=True,
                        to="knowledge_base.knowledgedocument",
                        verbose_name="相关文档",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="查询用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识查询",
                "verbose_name_plural": "知识查询",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEntityDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.JSONField(default=dict, verbose_name="位置信息")),
                ("context", models.TextField(verbose_name="上下文")),
                ("confidence", models.FloatField(default=0.0, verbose_name="置信度")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge_base.knowledgedocument",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge_base.knowledgeentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "实体-文档关联",
                "verbose_name_plural": "实体-文档关联",
                "unique_together": {("entity", "document")},
            },
        ),
        migrations.AddField(
            model_name="knowledgeentity",
            name="documents",
            field=models.ManyToManyField(
                related_name="entities",
                through="knowledge_base.KnowledgeEntityDocument",
                to="knowledge_base.knowledgedocument",
                verbose_name="关联文档",
            ),
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField(verbose_name="块索引")),
                ("content", models.TextField(verbose_name="块内容")),
                ("content_length", models.IntegerField(verbose_name="内容长度")),
                ("embedding", models.JSONField(default=list, verbose_name="向量表示")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("embedding", "向量化中"),
                            ("indexed", "已索引"),
                            ("failed", "处理失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="块状态",
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge_base.knowledgedocument",
                        verbose_name="所属文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档块",
                "verbose_name_plural": "文档块",
                "ordering": ["chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation_type", models.CharField(max_length=50, verbose_name="关系类型")),
                ("description", models.TextField(blank=True, verbose_name="关系描述")),
                ("confidence", models.FloatField(default=0.0, verbose_name="置信度")),
                ("properties", models.JSONField(default=dict, verbose_name="关系属性")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="knowledge_base.knowledgeentity",
                        verbose_name="源实体",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="knowledge_base.knowledgeentity",
                        verbose_name="目标实体",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识关系",
                "verbose_name_plural": "知识关系",
                "ordering": ["relation_type"],
                "unique_together": {
                    ("source_entity", "target_entity", "relation_type")
                },
            },
        ),
    ]
