# Generated by Django 4.2.27 on 2026-01-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_id",
                    models.CharField(max_length=50, unique=True, verbose_name="用例编号"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="用例标题")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FUNCTION", "功能测试"),
                            ("BOUNDARY", "边界测试"),
                            ("EXCEPTION", "异常测试"),
                            ("PERFORMANCE", "性能测试"),
                        ],
                        max_length=20,
                        verbose_name="测试类型",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P0", "P0-核心流程"),
                            ("P1", "P1-重要功能"),
                            ("P2", "P2-一般功能"),
                        ],
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                ("precondition", models.TextField(blank=True, verbose_name="前置条件")),
                ("steps", models.JSONField(verbose_name="测试步骤")),
                ("expected_result", models.TextField(verbose_name="预期结果")),
                (
                    "dubbo_interface",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Dubbo接口"
                    ),
                ),
                (
                    "dubbo_method",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Dubbo方法"
                    ),
                ),
                (
                    "dubbo_params",
                    models.JSONField(default=dict, verbose_name="Dubbo参数"),
                ),
                (
                    "dubbo_group",
                    models.CharField(blank=True, max_length=50, verbose_name="Dubbo分组"),
                ),
                (
                    "dubbo_version",
                    models.CharField(blank=True, max_length=20, verbose_name="Dubbo版本"),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待评审"),
                            ("APPROVED", "已通过"),
                            ("REJECTED", "需修改"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="评审状态",
                    ),
                ),
                ("review_comment", models.TextField(blank=True, verbose_name="评审意见")),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="评审时间"),
                ),
                (
                    "execution_count",
                    models.IntegerField(default=0, verbose_name="执行次数"),
                ),
                (
                    "last_execution_status",
                    models.CharField(blank=True, max_length=20, verbose_name="最后执行状态"),
                ),
                (
                    "last_executed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后执行时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例管理",
                "db_table": "test_case",
            },
        ),
        migrations.CreateModel(
            name="TestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_batch",
                    models.CharField(max_length=100, verbose_name="执行批次"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "执行中"),
                            ("PASSED", "通过"),
                            ("FAILED", "失败"),
                            ("ERROR", "错误"),
                        ],
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                ("request_data", models.JSONField(null=True, verbose_name="请求数据")),
                ("response_data", models.JSONField(null=True, verbose_name="响应数据")),
                ("execution_time", models.FloatField(verbose_name="执行耗时(秒)")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                ("stack_trace", models.TextField(blank=True, verbose_name="堆栈信息")),
                (
                    "executed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="执行时间"),
                ),
            ],
            options={
                "verbose_name": "测试执行",
                "verbose_name_plural": "测试执行记录",
                "db_table": "test_execution",
            },
        ),
        migrations.CreateModel(
            name="TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(max_length=100, unique=True, verbose_name="批次ID"),
                ),
                ("total_cases", models.IntegerField(verbose_name="总用例数")),
                ("passed_cases", models.IntegerField(verbose_name="通过数")),
                ("failed_cases", models.IntegerField(verbose_name="失败数")),
                ("error_cases", models.IntegerField(verbose_name="错误数")),
                ("skipped_cases", models.IntegerField(default=0, verbose_name="跳过数")),
                ("pass_rate", models.FloatField(verbose_name="通过率(%)")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("duration", models.FloatField(verbose_name="总耗时(秒)")),
                (
                    "report_file",
                    models.FileField(upload_to="reports/", verbose_name="报告文件"),
                ),
                ("environment", models.JSONField(default=dict, verbose_name="环境信息")),
                ("failed_details", models.JSONField(default=list, verbose_name="失败详情")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "测试报告",
                "verbose_name_plural": "测试报告",
                "db_table": "test_report",
            },
        ),
    ]
