# Generated by Django 4.2.27 on 2026-01-20 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("prd_review", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("code_review", "0002_initial"),
        ("test_case", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testreport",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="test_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="test_case.testcase",
                verbose_name="测试用例",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="code_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="code_review.codereview",
                verbose_name="关联代码评审",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_test_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="prd_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prd_review.prdreview",
                verbose_name="关联PRD评审",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_test_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="评审人",
            ),
        ),
        migrations.AddIndex(
            model_name="testreport",
            index=models.Index(
                fields=["batch_id"], name="test_report_batch_i_9265a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testreport",
            index=models.Index(
                fields=["created_at"], name="test_report_created_9f935d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testexecution",
            index=models.Index(
                fields=["test_case"], name="test_execut_test_ca_f7db05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testexecution",
            index=models.Index(
                fields=["execution_batch"], name="test_execut_executi_24722f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testexecution",
            index=models.Index(fields=["status"], name="test_execut_status_87fdd9_idx"),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["prd_review"], name="test_case_prd_rev_6f704b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(fields=["type"], name="test_case_type_0809a7_idx"),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["priority"], name="test_case_priorit_7ad5a7_idx"
            ),
        ),
    ]
