# Generated by Django 4.2.27 on 2026-01-22 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prd_review", "0002_initial"),
        ("code_review", "0003_reviewtask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_case", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCaseGenerationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Celery任务ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待中"),
                            ("ANALYZING", "分析中"),
                            ("AI_GENERATING", "AI生成中"),
                            ("PARSING", "解析结果中"),
                            ("SAVING", "保存用例中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度(0-100)")),
                (
                    "current_step",
                    models.CharField(blank=True, max_length=200, verbose_name="当前步骤"),
                ),
                ("total_cases", models.IntegerField(default=0, verbose_name="生成用例总数")),
                (
                    "generated_cases",
                    models.IntegerField(default=0, verbose_name="已生成用例数"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "code_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="code_review.codereview",
                        verbose_name="关联代码评审",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "prd_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prd_review.prdreview",
                        verbose_name="关联PRD评审",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例生成任务",
                "verbose_name_plural": "测试用例生成任务",
                "db_table": "test_case_generation_task",
                "indexes": [
                    models.Index(
                        fields=["task_id"], name="test_case_g_task_id_9732cb_idx"
                    ),
                    models.Index(
                        fields=["status"], name="test_case_g_status_c8907f_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="test_case_g_created_faf251_idx"
                    ),
                ],
            },
        ),
    ]
