# Generated by Django 4.2.27 on 2026-01-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedbackRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("WHITELIST", "白名单-忽略"), ("BLACKLIST", "黑名单-加强检测")],
                        max_length=20,
                        verbose_name="规则类型",
                    ),
                ),
                ("pattern", models.TextField(verbose_name="规则模式")),
                ("description", models.TextField(blank=True, verbose_name="规则描述")),
                ("weight", models.FloatField(default=1.0, verbose_name="权重")),
                ("feedback_count", models.IntegerField(default=0, verbose_name="反馈次数")),
                (
                    "accuracy_rate",
                    models.FloatField(default=0.0, verbose_name="准确率(%)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "反馈规则",
                "verbose_name_plural": "反馈规则管理",
                "db_table": "feedback_rule",
            },
        ),
    ]
