# Generated by Django 4.2.27 on 2026-02-03 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("repository", "0004_repository_auto_review_on_new_commit_and_more"),
        ("knowledge_base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="对话标题")),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("code_review", "代码评审"),
                            ("prd_review", "PRD评审"),
                            ("test_case", "测试用例"),
                            ("knowledge", "知识库问答"),
                            ("general", "通用对话"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="对话类型",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge_base.knowledgedocument",
                        verbose_name="关联知识库",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="repository.repository",
                        verbose_name="关联仓库",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "对话会话",
                "verbose_name_plural": "对话会话",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "用户"), ("assistant", "助手"), ("system", "系统")],
                        max_length=10,
                        verbose_name="消息角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "knowledge_references",
                    models.JSONField(blank=True, default=list, verbose_name="知识库引用"),
                ),
                (
                    "tokens_used",
                    models.IntegerField(default=0, verbose_name="使用的Token数"),
                ),
                (
                    "response_time",
                    models.FloatField(default=0.0, verbose_name="响应时间（秒）"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_chat.conversation",
                        verbose_name="对话会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "对话消息",
                "verbose_name_plural": "对话消息",
                "ordering": ["created_at"],
            },
        ),
    ]
