# Generated by Django 3.2.25 on 2026-02-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, help_text='存储多轮对话的槽位数据', verbose_name='上下文数据'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='current_mode',
            field=models.CharField(default='chat', help_text='chat, code_review_flow, agent_rag', max_length=50, verbose_name='当前模式'),
        ),
    ]
