# Generated by Django 3.2.25 on 2026-02-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_auto_20260225_2135'),
    ]

    operations = [
    ]
