# Generated by Django 4.2.27 on 2026-01-22 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("repository", "0003_repository_review_all_branches_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prd_review", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="文档标题")),
                ("file", models.FileField(upload_to="knowledge/", verbose_name="文档文件")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("prd", "PRD文档"),
                            ("code", "代码文档"),
                            ("api", "API文档"),
                            ("requirement", "需求文档"),
                            ("other", "其他文档"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="文档类型",
                    ),
                ),
                ("file_size", models.IntegerField(verbose_name="文件大小(bytes)")),
                (
                    "is_embedded",
                    models.BooleanField(default=False, verbose_name="是否已向量化"),
                ),
                ("chunk_count", models.IntegerField(default=0, verbose_name="文档块数量")),
                (
                    "embedding_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("EMBEDDING", "向量化中"),
                            ("INDEXED", "已索引"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="向量化状态",
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_docs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "prd_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_docs",
                        to="prd_review.prdreview",
                        verbose_name="关联PRD评审",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_docs",
                        to="repository.repository",
                        verbose_name="关联仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库文档",
                "verbose_name_plural": "知识库文档",
                "db_table": "knowledge_document",
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField(verbose_name="文档块索引")),
                ("content", models.TextField(verbose_name="文档块内容")),
                ("content_length", models.IntegerField(verbose_name="内容长度")),
                (
                    "embedding",
                    models.JSONField(blank=True, null=True, verbose_name="向量表示"),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("EMBEDDING", "向量化中"),
                            ("INDEXED", "已索引"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge_base.knowledgedocument",
                        verbose_name="所属文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档块",
                "verbose_name_plural": "文档块",
                "db_table": "document_chunk",
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(max_length=100, unique=True, verbose_name="会话ID"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="会话标题")),
                ("message_count", models.IntegerField(default=0, verbose_name="消息数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "prd_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to="prd_review.prdreview",
                        verbose_name="关联PRD评审",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to="repository.repository",
                        verbose_name="关联仓库",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI对话会话",
                "verbose_name_plural": "AI对话会话",
                "db_table": "chat_session",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("assistant", "AI助手"),
                            ("system", "系统"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "retrieved_docs",
                    models.JSONField(default=list, verbose_name="检索到的文档"),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="knowledge_base.chatsession",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI对话消息",
                "verbose_name_plural": "AI对话消息",
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["file_type"], name="knowledge_d_file_ty_dbb055_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["is_embedded"], name="knowledge_d_is_embe_bcb157_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["created_at"], name="knowledge_d_created_596f28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="document_ch_documen_a45e27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(fields=["status"], name="document_ch_status_88cf34_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["session_id"], name="chat_sessio_session_b18b4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["user"], name="chat_sessio_user_id_beb7da_idx"),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["created_at"], name="chat_sessio_created_3b61f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="chat_messag_session_4940cf_idx"
            ),
        ),
    ]
