# Generated by Django 4.2.27 on 2026-01-29 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("repository", "0004_repository_auto_review_on_new_commit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meeting_title",
                    models.CharField(max_length=200, verbose_name="会议标题"),
                ),
                (
                    "meeting_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="会议时间"
                    ),
                ),
                ("participants", models.TextField(verbose_name="参会人员（逗号分隔的用户名）")),
                ("audio_file", models.CharField(max_length=500, verbose_name="音频文件路径")),
                (
                    "audio_file_original_name",
                    models.CharField(max_length=200, verbose_name="原始文件名"),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=0, help_text="时长(秒)", verbose_name="时长"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, help_text="文件大小(字节)", verbose_name="文件大小"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "已上传"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "transcript_count",
                    models.IntegerField(default=0, verbose_name="转写条数"),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理完成时间"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="repository.repository",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "会议录音",
                "verbose_name_plural": "会议录音",
                "db_table": "meeting_recording",
                "ordering": ["-upload_time"],
            },
        ),
        migrations.CreateModel(
            name="MeetingSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="纪要标题")),
                ("summary_text", models.TextField(verbose_name="会议摘要")),
                (
                    "key_points",
                    models.JSONField(
                        default=list, help_text="讨论要点", verbose_name="讨论要点"
                    ),
                ),
                (
                    "decisions",
                    models.JSONField(
                        default=list, help_text="决策事项", verbose_name="决策事项"
                    ),
                ),
                (
                    "action_items",
                    models.JSONField(
                        default=list, help_text="待办任务", verbose_name="待办任务"
                    ),
                ),
                (
                    "markdown_file",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Markdown文件"
                    ),
                ),
                (
                    "pdf_file",
                    models.CharField(blank=True, max_length=500, verbose_name="PDF文件"),
                ),
                (
                    "docx_file",
                    models.CharField(blank=True, max_length=500, verbose_name="Word文件"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(
                        choices=[("auto", "自动生成"), ("manual", "人工编辑")],
                        default="auto",
                        max_length=20,
                        verbose_name="生成方式",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "recording",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="meeting_assistant.meetingrecording",
                        verbose_name="录音",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_summaries",
                        to="repository.repository",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "会议纪要",
                "verbose_name_plural": "会议纪要",
                "db_table": "meeting_summary",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingTranscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "speaker",
                    models.CharField(
                        help_text="如 spk0, spk1", max_length=50, verbose_name="说话人标识"
                    ),
                ),
                ("content", models.TextField(verbose_name="转写内容")),
                (
                    "start_time",
                    models.FloatField(help_text="开始时间(秒)", verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.FloatField(help_text="结束时间(秒)", verbose_name="结束时间"),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="识别置信度(0-1)", verbose_name="置信度"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="meeting_assistant.meetingrecording",
                        verbose_name="录音",
                    ),
                ),
                (
                    "speaker_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="可以手动关联到系统用户",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "会议转写",
                "verbose_name_plural": "会议转写",
                "db_table": "meeting_transcript",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="ReviewOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opinion_type",
                    models.CharField(
                        choices=[
                            ("issue", "问题"),
                            ("suggestion", "建议"),
                            ("decision", "决策"),
                            ("risk", "风险"),
                            ("positive", "肯定意见"),
                        ],
                        max_length=20,
                        verbose_name="意见类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="意见内容")),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "高"), ("medium", "中"), ("low", "低")],
                        default="medium",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="是否已解决"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="解决时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="说话人",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinions",
                        to="meeting_assistant.meetingsummary",
                        verbose_name="会议纪要",
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        blank=True,
                        help_text="对应的转写片段",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meeting_assistant.meetingtranscript",
                        verbose_name="转写片段",
                    ),
                ),
            ],
            options={
                "verbose_name": "评审意见",
                "verbose_name_plural": "评审意见",
                "db_table": "review_opinion",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["summary", "opinion_type"],
                        name="review_opin_summary_b8ac2a_idx",
                    ),
                    models.Index(
                        fields=["speaker"], name="review_opin_speaker_c3a8b4_idx"
                    ),
                    models.Index(
                        fields=["is_resolved"], name="review_opin_is_reso_dc8b15_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="meetingtranscript",
            index=models.Index(
                fields=["recording", "start_time"],
                name="meeting_tra_recordi_940d87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingtranscript",
            index=models.Index(
                fields=["speaker"], name="meeting_tra_speaker_b346aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingsummary",
            index=models.Index(
                fields=["recording"], name="meeting_sum_recordi_a5ff12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingsummary",
            index=models.Index(
                fields=["repository", "-generated_at"],
                name="meeting_sum_reposit_3d01ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingsummary",
            index=models.Index(fields=["status"], name="meeting_sum_status_08bda2_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingrecording",
            index=models.Index(
                fields=["repository", "-upload_time"],
                name="meeting_rec_reposit_268d2c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingrecording",
            index=models.Index(fields=["status"], name="meeting_rec_status_d23967_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingrecording",
            index=models.Index(
                fields=["created_by"], name="meeting_rec_created_bb31ed_idx"
            ),
        ),
    ]
