# Generated by Django 4.2.27 on 2026-01-29 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0004_repository_auto_review_on_new_commit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meeting_assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("person", "人员"),
                            ("project", "项目"),
                            ("topic", "主题"),
                            ("issue", "问题"),
                            ("technology", "技术"),
                            ("decision", "决策"),
                        ],
                        max_length=20,
                        verbose_name="实体类型",
                    ),
                ),
                ("entity_name", models.CharField(max_length=200, verbose_name="实体名称")),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                ("confidence", models.FloatField(default=1.0, verbose_name="置信度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meeting_assistant.meetingrecording",
                        verbose_name="关联会议",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="repository.repository",
                        verbose_name="关联仓库",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识实体",
                "verbose_name_plural": "知识实体",
                "db_table": "knowledge_entity",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("attended", "参会"),
                            ("discussed", "讨论"),
                            ("raised", "提出"),
                            ("resolved", "解决"),
                            ("related_to", "相关"),
                            ("mentioned", "提及"),
                            ("decided", "决定"),
                        ],
                        max_length=20,
                        verbose_name="关系类型",
                    ),
                ),
                ("properties", models.JSONField(default=dict, verbose_name="关系属性")),
                ("confidence", models.FloatField(default=1.0, verbose_name="置信度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="meeting_assistant.knowledgeentity",
                        verbose_name="源实体",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meeting_assistant.meetingsummary",
                        verbose_name="关联纪要",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="meeting_assistant.knowledgeentity",
                        verbose_name="目标实体",
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meeting_assistant.meetingtranscript",
                        verbose_name="关联转写",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识关系",
                "verbose_name_plural": "知识关系",
                "db_table": "knowledge_relation",
                "indexes": [
                    models.Index(
                        fields=["source", "target"],
                        name="knowledge_r_source__bed05a_idx",
                    ),
                    models.Index(
                        fields=["relation_type"], name="knowledge_r_relatio_bd95dc_idx"
                    ),
                    models.Index(
                        fields=["summary"], name="knowledge_r_summary_2e0fdb_idx"
                    ),
                ],
                "unique_together": {("source", "target", "relation_type")},
            },
        ),
        migrations.AddIndex(
            model_name="knowledgeentity",
            index=models.Index(
                fields=["entity_type", "entity_name"],
                name="knowledge_e_entity__9764b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentity",
            index=models.Index(fields=["user"], name="knowledge_e_user_id_3b0783_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgeentity",
            index=models.Index(
                fields=["repository"], name="knowledge_e_reposit_6fcd58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentity",
            index=models.Index(
                fields=["meeting"], name="knowledge_e_meeting_2bf9b1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgeentity",
            unique_together={("entity_type", "entity_name")},
        ),
    ]
