# Generated by Django 4.2.27 on 2026-01-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meeting_assistant", "0002_knowledgeentity_knowledgerelation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingsummary",
            name="template_type",
            field=models.CharField(default="会议纪要", max_length=50, verbose_name="模板类型"),
        ),
        migrations.AddField(
            model_name="meetingsummary",
            name="user_notes",
            field=models.JSONField(default=list, help_text="用户笔记", verbose_name="用户笔记"),
        ),
        migrations.AddField(
            model_name="meetingsummary",
            name="user_todos",
            field=models.JSONField(default=list, help_text="用户待办", verbose_name="用户待办"),
        ),
    ]
