# Generated by Django 4.2.27 on 2026-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meeting_assistant", "0003_meetingsummary_template_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingsummary",
            name="image_file",
            field=models.CharField(blank=True, max_length=500, verbose_name="图片文件"),
        ),
    ]
