# Generated by Django 3.2.25 on 2026-02-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, verbose_name='配置名称')),
                ('api_base', models.CharField(default='https://api.deepseek.com/v1', max_length=255, verbose_name='API地址')),
                ('api_key', models.CharField(max_length=255, verbose_name='API密钥')),
                ('model_name', models.CharField(default='deepseek-chat', max_length=100, verbose_name='模型名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '大模型配置',
                'verbose_name_plural': '大模型配置',
                'db_table': 'platform_llm_config',
            },
        ),
    ]
