# Generated by Django 4.2.27 on 2026-01-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PRDReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="PRD标题")),
                ("file", models.FileField(upload_to="prd/", verbose_name="PRD文件")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("word", "Word文档"),
                            ("md", "Markdown"),
                            ("pdf", "PDF"),
                        ],
                        max_length=20,
                        verbose_name="文件类型",
                    ),
                ),
                ("file_size", models.IntegerField(verbose_name="文件大小(bytes)")),
                ("background", models.TextField(blank=True, verbose_name="背景描述")),
                ("user_stories", models.JSONField(default=list, verbose_name="用户故事")),
                ("requirements", models.JSONField(default=list, verbose_name="需求点")),
                ("completeness_score", models.FloatField(verbose_name="完整性得分(0-1)")),
                ("consistency_score", models.FloatField(verbose_name="一致性得分(0-1)")),
                ("risk_score", models.FloatField(verbose_name="风险得分(0-1)")),
                ("overall_score", models.FloatField(verbose_name="综合得分(0-1)")),
                ("ai_suggestions", models.TextField(verbose_name="AI改进建议")),
                ("issues_found", models.JSONField(default=list, verbose_name="发现的问题")),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待评审"),
                            ("APPROVED", "已通过"),
                            ("REJECTED", "需修改"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="评审状态",
                    ),
                ),
                ("review_comment", models.TextField(blank=True, verbose_name="评审意见")),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="评审时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "PRD评审",
                "verbose_name_plural": "PRD评审记录",
                "db_table": "prd_review",
            },
        ),
    ]
