# Generated by Django 4.2.27 on 2026-01-20 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prd_review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prdreview",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_prds",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="prdreview",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prd_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="评审人",
            ),
        ),
        migrations.AddIndex(
            model_name="prdreview",
            index=models.Index(
                fields=["created_by"], name="prd_review_created_3dd6e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prdreview",
            index=models.Index(
                fields=["review_status"], name="prd_review_review__7ae890_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prdreview",
            index=models.Index(
                fields=["overall_score"], name="prd_review_overall_8d0c41_idx"
            ),
        ),
    ]
