# Generated by Django 4.2.27 on 2026-01-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prd_review", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prdreview",
            name="description",
            field=models.TextField(blank=True, verbose_name="PRD描述"),
        ),
    ]
