# Generated by Django 4.2.27 on 2026-01-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="仓库名称")),
                ("git_url", models.URLField(verbose_name="Git仓库地址")),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("password", "用户名密码"), ("ssh", "SSH Key")],
                        default="password",
                        max_length=20,
                        verbose_name="认证方式",
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=100, verbose_name="用户名"),
                ),
                (
                    "password_encrypted",
                    models.CharField(blank=True, max_length=500, verbose_name="密码（加密）"),
                ),
                (
                    "ssh_key_encrypted",
                    models.TextField(blank=True, verbose_name="SSH Key（加密）"),
                ),
                ("local_path", models.CharField(max_length=500, verbose_name="本地克隆路径")),
                (
                    "dingtalk_webhook",
                    models.URLField(blank=True, verbose_name="钉钉Webhook"),
                ),
                (
                    "dingtalk_secret",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="钉钉Secret"
                    ),
                ),
                (
                    "high_risk_threshold",
                    models.FloatField(default=0.7, verbose_name="高风险阈值"),
                ),
                (
                    "medium_risk_threshold",
                    models.FloatField(default=0.4, verbose_name="中风险阈值"),
                ),
                (
                    "critical_patterns",
                    models.JSONField(
                        default=list,
                        help_text='[{"pattern": "**/Controller.java", "level": "critical"}]',
                        verbose_name="关键文件规则",
                    ),
                ),
                (
                    "ignore_patterns",
                    models.JSONField(
                        default=list,
                        help_text='[{"pattern": "**/*.md", "type": "ignore"}]',
                        verbose_name="忽略规则",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Git仓库",
                "verbose_name_plural": "仓库管理",
                "db_table": "repository",
            },
        ),
    ]
