# Generated by Django 4.2.27 on 2026-01-20 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("repository", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["is_active"], name="repository_is_acti_ef9396_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["created_by"], name="repository_created_4c7833_idx"
            ),
        ),
    ]
