# Generated by Django 4.2.27 on 2026-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="review_all_branches",
            field=models.BooleanField(
                default=False, help_text="是否评审所有分支的提交", verbose_name="评审所有分支"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="review_branch",
            field=models.CharField(
                default="master",
                help_text='指定要评审的分支,设置为"all"则评审所有分支',
                max_length=100,
                verbose_name="评审分支",
            ),
        ),
    ]
