# Generated by Django 4.2.27 on 2026-01-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0003_repository_review_all_branches_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="auto_review_on_new_commit",
            field=models.BooleanField(
                default=True, help_text="实时监控发现新提交时自动触发评审", verbose_name="新提交自动评审"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="enable_manual_review",
            field=models.BooleanField(
                default=True, help_text="允许用户手动触发代码评审", verbose_name="启用手动触发"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="enable_realtime_monitor",
            field=models.BooleanField(
                default=False, help_text="实时监控代码提交，发现新提交立即触发评审", verbose_name="启用实时监控"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="enable_scheduled_review",
            field=models.BooleanField(
                default=False, help_text="按照定时规则自动触发代码评审", verbose_name="启用定时评审"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="notify_on_review_complete",
            field=models.BooleanField(
                default=True, help_text="评审完成后发送钉钉通知", verbose_name="评审完成通知"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="notify_risk_threshold",
            field=models.CharField(
                default="MEDIUM",
                help_text="风险等级达到此级别时才发送通知: HIGH/MEDIUM/LOW",
                max_length=20,
                verbose_name="通知风险阈值",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="realtime_monitor_branches",
            field=models.JSONField(
                default=list,
                help_text='要监控的分支列表，例如: ["master", "develop"]',
                verbose_name="实时监控分支",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="realtime_monitor_interval",
            field=models.IntegerField(
                default=60, help_text="检查新提交的间隔时间，默认60秒", verbose_name="实时监控间隔（秒）"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="scheduled_review_cron",
            field=models.CharField(
                blank=True,
                default="",
                help_text="例如: 0 12 * * * 表示每天中午12点",
                max_length=100,
                verbose_name="定时评审Cron表达式",
            ),
        ),
    ]
